### PR TITLE
[sinewave] simple 3d sinusoidal wave patter

### PR DESCRIPTION
**Pull request by oyfo**
Sinewave

### CODE REVIEW

**Comment by ultrafez** [comment]
Thanks for raising a PR for this pattern, it looks great! I first tried running it with Python 2.7 and I got the following error - would you mind fixing the list index access so it works in both versions of Python? We use Python 2.7 when running the large cube for Light Night (as far as I remember) so it's good for us to maintain compatibility with both versions.

```
$ python cube.py --pattern sinewave
2017-09-28 01:38:13.444 Python[59833:1943970] 01:38:13.442 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
No handlers could be found for logger "OpenGL.arrays.numpymodule"
Loading pattern module 'sinewave'
Running pattern sinewave
Traceback (most recent call last):
  File "cube.py", line 165, in <module>
    run_pattern(c, p)
  File "cube.py", line 87, in run_pattern
    pattern.tick()
  File "/Users/alex/Documents/pycubedemo/patterns/sinewave.py", line 68, in tick
    self.cube.set_pixel((x, y, z), rainbow(self.iter+x, 10))
  File "/Users/alex/Documents/pycubedemo/glcube.py", line 103, in set_pixel
    self.pixels[tuple(xyz)] = rgb
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

When I ran it with Python 3.6, I noticed there was an empty row or two for each peak of the sine wave - I can't dig into the code right now, but I suspect it might be because the jump in the value of `sin(x)` between two integer values of `x` is more than 1 on the y-axis. See 2 gaps in the screenshot:

image

**Comment by oyfo** [comment]
I have updated version ready. I have seen this error when I used new simulator (I need to cast one value to INT to make it work). Also solved empty row problem. I will push changes tomorrow.

**Comment by ultrafez** [comment]
Perfect :) look forward to seeing the tweaked version! You might have found a bug in my WebGL simulator, I'll ask you more about that tomorrow to see if it's something I need to fix on my side.

**Comment by ultrafez** [comment]
Looks great, thanks very much :)

**Pull request merged**
